### PR TITLE
Fix path delimiting (#22)

### LINKED ISSUE #22: Trailing slashes are appended to all endpoints
Note: total beginner, so apologies if I've missed something obvious.

I've been testing some external APIs using `servant-quickcheck == 0.0.2.2` (and `servant == 0.8.1`) via `lts-7.19`, but getting errors that seemed strange... until I looked at the app logs and saw trailing slashes on every incoming request (the endpoints in that API didn't allow for this). 

However I structure the API definition, Servant-* seems to be appending a trailing slash. I assumed it was me, but I made a simple test project with an API like:

```
type API = "path" :> Get '[JSON] Int
```
and watching the raw HTTP (in `netcat`) get:
```
GET /path/ HTTP/1.1
Host: localhost:8080
Accept-Encoding: gzip
```

Then when defining multi-part paths using multiple `:>` (as [I understand is correct](https://haskell-servant.readthedocs.io/en/stable/tutorial/ApiType.html#static-strings)), 
```
type API = "path" :> "sub" :> Get '[JSON] Int
```
I get 

```
GET /pathsub/ HTTP/1.1
Host: localhost:8080
Accept-Encoding: gzip
```

Any ideas?

### PR DESCRIPTION
**Pull request by declension**
* Add test API with multiple Path elements
  * Add basic test using this API, generating an endpoint to validate that query path delimiting is happening correctly (that fails on `master`)
  * Fix (re)creation of path to prepend `/` to each new path section, but only if it's non-empty (this fixes the trailing slashes, but still allows users to use a `:> "foo/" :>...` if their API demands trailing slashes)
  * Update / fix the existing test that now fails slightly differently (i.e. the trailing slash in `failplz/` is gone)

Fixes #22.

### CODE REVIEW

**Comment by declension** [comment]
@jkarni Thanks for the release with #23 BTW - sorry I didn't get to push _this_ in time (though maybe you guys prefer separate releases anyway)

**Comment by jkarni** [comment]
No problem on not making it for the release - it wasn't a major version change so I'm happy making many of those.

**Comment by declension** [comment]
Thanks!

**Comment by jkarni** [comment]
On hackage as 0.0.2.4.

**Pull request merged**
