### PR TITLE
Upgrade hspec to 2.4.4 and use safeEvaluateExample for tests

### LINKED ISSUE #27: Support hspec >= 2.4
Things seem to have changed internally, causing failures that were previously caught to be failures again.

### PR DESCRIPTION
**Pull request by erewok**
## Description

- Bumps Hspec dependency to 2.4.4.
- Tests: adds `show` to `err` in order to convert from `FailureReason` -> String.
- Tests: Switch to `safeEvaluateExample` in order to capture failure output and make assertions about it.

Fixes #27 .

## Notes

- hspec 2.4.0 changed `Fail` constructor to `Failure` and the constructor takes a `FailureReason`: `Failure (Maybe Location) FailureReason`

### CODE REVIEW

**Comment by erewok** [comment]
Build failures in Travis are due to stack-lts-6 and stack-lts-7. Is there a clean way of supporting multiple versions of a library (hspec, in this case) for these tests and do want to try to do that?

**Comment by psibi** [comment]
@erewok You have to likely change the relevant yaml files and update the `extra-deps` section with the updated package.

**Comment by erewok** [comment]
@psibi I did try that, but `hspec>=2.4` is not available in the package sets for `lts-6` and the changes in 2.4 are breaking changes. In particular, they renamed a constructor used in the tests for this project.

The relevant code is in tests for this project, so in order to continue supporting `lts-6`, `lts-7`, and `lts-8`, we'd have to have different versions of `hspec` and related dependencies installed and then check for versions and write different test code depending on the installed version.

**Comment by jkarni** [comment]
@erewok thanks a lot again!

**Pull request merged**
